apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: videoapp
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: ""
spec:
  type: NodePort
  selector:
    app: frontend-service
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 32198
  externalIPs:
    - 192.168.181.100
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  sessionAffinity: None

