apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-volume-mongodb-0
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  hostPath:
    path: /opt/local-path-provisioner/mongodb
  persistentVolumeReclaimPolicy: Retain
