apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-volume-mongodb-0
  namespace: videoapp
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
