apiVersion: apps/v1
kind: Deployment
metadata:
  name: converter-service
  namespace: videoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: converter-service
  template:
    metadata:
      labels:
        app: converter-service
    spec:
      containers:
        - name: converter-service
          image: chiomavee/converter-service:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: videoapp-secrets
