apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: videoapp
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
