apiVersion: v1
kind: Secret
metadata:
  name: videoapp-secrets
  namespace: videoapp
type: Opaque
stringData:
  # MongoDB URIs
  MONGO_URI: mongodb://root:mongopassword@mongodb.videoapp.svc.cluster.local:27017/videoapp
  MONGODB_VIDEOS_URI: mongodb://root:mongopassword@mongodb.videoapp.svc.cluster.local:27017/videoapp
  MONGODB_MP3S_URI: mongodb://root:mongopassword@mongodb.videoapp.svc.cluster.local:27017/videoapp
  MONGODB_URI: mongodb://root:mongopassword@mongodb.videoapp.svc.cluster.local:27017/videoapp

  # PostgreSQL for auth-service
  POSTGRES_HOST: postgresql.videoapp.svc.cluster.local
  POSTGRES_PORT: "5432"
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgrespassword

  # Also needed by the Python code (DATABASE_* aliases)
  DATABASE_HOST: postgresql.videoapp.svc.cluster.local
  DATABASE_PORT: "5432"
  DATABASE_NAME: postgres
  DATABASE_USER: postgres
  DATABASE_PASSWORD: postgrespassword

  # RabbitMQ for converter and notification services
  RABBITMQ_HOST: rabbitmq.videoapp.svc.cluster.local
  RABBITMQ_PORT: "5672"
  RABBITMQ_USER: guest
  RABBITMQ_PASSWORD: guestpassword
  VIDEO_QUEUE: video

  # Email credentials for notification-service
  EMAIL_USER: vanessaegwuibe08@gmail.com
  EMAIL_PASSWORD: ysdrywalqqppcbhh

  # JWT secret for auth-service
  JWT_SECRET: myjwtsecret

  # MongoDB container startup credentials (required for mongo image)
  MONGO_ROOT_USERNAME: root
  MONGO_ROOT_PASSWORD: mongopassword
