apiVersion: v1
kind: Secret
metadata:
  name: videoapp-secrets
  namespace: videoapp
type: Opaque
stringData:
  # MongoDB URIs
  MONGO_URI: mongodb://mongoUser:mongoPass@mongodb.videoapp.svc.cluster.local:27017/videoapp
  MONGODB_VIDEOS_URI: mongodb://mongoUser:mongoPass@mongodb.videoapp.svc.cluster.local:27017/videoapp
  MONGODB_MP3S_URI: mongodb://mongoUser:mongoPass@mongodb.videoapp.svc.cluster.local:27017/videoapp
  MONGODB_URI: mongodb://mongoUser:mongoPass@mongodb.videoapp.svc.cluster.local:27017/videoapp

  # PostgreSQL for auth-service
  POSTGRES_HOST: postgresql.videoapp.svc.cluster.local
  POSTGRES_PORT: "5432"
  POSTGRES_DB: authdb
  POSTGRES_USER: authuser
  POSTGRES_PASSWORD: authpass

  # DATABASE_* aliases
  DATABASE_HOST: postgresql.videoapp.svc.cluster.local
  DATABASE_PORT: "5432"
  DATABASE_NAME: authdb
  DATABASE_USER: authuser
  DATABASE_PASSWORD: authpass

  # RabbitMQ
  RABBITMQ_HOST: rabbitmq.videoapp.svc.cluster.local
  RABBITMQ_PORT: "5672"
  RABBITMQ_USER: videoapp
  RABBITMQ_PASSWORD: strongpassword
  VIDEO_QUEUE: video

  # Email credentials
  EMAIL_USER: vanessaegwuibe08@gmail.com
  EMAIL_PASSWORD: ysdrywalqqppcbhh

  # JWT
  JWT_SECRET: supersecurejwtsecret12345

  # MongoDB container startup
  MONGO_ROOT_USERNAME: root
  MONGO_ROOT_PASSWORD: mongopassword

  # Auth service address
  AUTH_SVC_ADDRESS: http://auth-service.videoapp.svc.cluster.local:80
