apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: videoapp
spec:
  selector:
    app: gateway-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000  # ✅ Matches container port
  type: NodePort
