apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: videoapp
spec:
  ports:
    - port: 5672
      name: amqp
    - port: 15672
      name: http
    - port: 4369
      name: epmd
    - port: 25672
      name: dist
  selector:
    app: rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-headless
  namespace: videoapp
spec:
  clusterIP: None
  selector:
    app: rabbitmq
  ports:
    - port: 5672
      name: amqp
    - port: 15672
      name: http
    - port: 4369
      name: epmd
    - port: 25672
      name: dist
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: videoapp
spec:
  serviceName: "rabbitmq-headless"
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          ports:
            - containerPort: 5672
            - containerPort: 15672
            - containerPort: 4369
            - containerPort: 25672
