apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: auth-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-app
      tier: db
  template:
    metadata:
      labels:
        app: auth-app
        tier: db
    spec:
      containers:
        - name: postgres
          image: {{ .Values.container.image }}
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: {{ .Values.container.env.user }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.container.env.password }}
            - name: POSTGRES_DB
              value: {{ .Values.container.env.db }}
