apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: videoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: chiomavee/notification-service:latest  # ✅ Use Docker Hub image
          imagePullPolicy: Always                       # ✅ Always pull latest from Docker Hub
          envFrom:
            - secretRef:
                name: videoapp-secrets
